export const MAX_TABLE_ROWS = 10_000
export const MAX_TABLE_COLUMNS = 100
export const AI_COLUMN_PREFIX = 'ai_'

export const TABLE_LIMITS = {
  MAX_ROWS: MAX_TABLE_ROWS,
  MAX_COLUMNS: MAX_TABLE_COLUMNS,
  MAX_AI_COLUMNS: 10,
  MAX_BATCH_INSERT_SIZE: 500,
  MAX_BULK_OPERATION_SIZE: 1_000,
  DEFAULT_QUERY_LIMIT: 100,
  MAX_QUERY_LIMIT: 1_000,
}
